source:       .
destination:  ./_site
markdown:     kramdown
permalink:    date
safe:         true
markdown_ext: md
collections:
  en:
    output: true
  fi:
    output: true
excerpt_separator: "\n\n"
