source:       .
destination:  ./_site
markdown:     kramdown
kramdown:
  parse_block_html: true # allow markdown in <div> etc.
permalink:    date
safe:         true
markdown_ext: md

collections:
  en:
    output: true
  fi:
    output: true
  usd:
    output: true

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
