source:       .
destination:  ./_site
markdown:     kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

baseurl: ""

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
  cs:
    output: true
  en:
    output: true
  sv:
    output: true
  fi:
    output: true
  af:
    output: true
  ar:
    output: true
  be:
    output: true
  bg:
    output: true
  ca:
    output: true
  ckb:
    output: true
  cop:
    output: true
  cu:
    output: true
  da:
    output: true
  dar:
    output: true
  de:
    output: true
  el:
    output: true
  es:
    output: true
  et:
    output: true
  eu:
    output: true
  fa:
    output: true
  fo:
    output: true
  fr:
    output: true
  fro:
    output: true
  ga:
    output: true
  gl:
    output: true
  got:
    output: true
  grc:
    output: true
  hsb:
    output: true
  hu:
    output: true
  hy:
    output: true
  it:
    output: true
  ja:
    output: true
  kk:
    output: true
  kmr:
    output: true
  ko:
    output: true
  la:
    output: true
  lv:
    output: true


excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.org/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
