source:       .
destination:  ./_site
markdown:     kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

baseurl: ""

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
#
# Czech
#
  cs:
    output: true
#
# English
#
  en:
    output: true
#
# Finnish
#
  fi:
    output: true
#
# Swedish
#
  sv:
    output: true
#
# Hungarian
#
  hu:
    output: true
#
# Irish
#
  ga:
    output: true
#
# Bulgarian
#
  bg:
    output: true
#
# Persian
#
  fa:
    output: true
#
# Hebrew
#
  he:
    output: true
#
# Spanish
#
  es:
    output: true
#
# French
#
  fr:
    output: true
#
# German
#
  de:
    output: true
#
# Greek
#
  el:
    output: true
#
# Basque
#
  eu:
    output: true
#
# Italian
#
  it:
    output: true
#
# Korean
#
  ko:
    output: true
#
# Japanese
#
  ja:
    output: true
#
# Chinese
#
  zh:
    output: true
#
# Romanian
#
  ro:
    output: true
#
# Slovenian
#
  sl:
    output: true
#
# Danish
#
  da:
    output: true
#
# Croatian
#
  hr:
    output: true
#
# Indonesian
#
  id:
    output: true
#
# Amharic
#
  am:
    output: true
#
# Hindi
#
  hi:
    output: true
#
# Ancient Greek
#
  grc:
    output: true
#
# Latin
#
  la:
    output: true
#
# Catalan
#
  ca:
    output: true
#
# Arabic
#
  ar:
    output: true
#
# Estonian
#
  et:
    output: true
#
# Portuguese
#
  pt:
    output: true
#
# Dutch
#
  nl:
    output: true
#
# Tamil
#
  ta:
    output: true
#
# Polish
#
  pl:
    output: true
#
# Norwegian
#
  no:
    output: true
#
# Church Slavonic
#
  cu:
    output: true
#
# Gothic
#
  got:
    output: true
#
# Kazakh
#
  kk:
    output: true
#
# Ukrainian
#
  uk:
    output: true
#
# Galician
#
  gl:
    output: true
#
# Russian
#
  ru:
    output: true
#
# Latvian
#
  lv:
    output: true
#
# Turkish
#
  tr:
    output: true
#
# Coptic
#
  cop:
    output: true
#
# Vietnamese
#
  vi:
    output: true
#
# Uralic
#
  urj:
    output: true
#
# Uyghur
#
  ug:
    output: true
#
# Buryat
#
  bxr:
    output: true
#
# Sanskrit
#
  sa:
    output: true
#
# Urdu
#
  ur:
    output: true
#
# Faroese
#
  fo:
    output: true
#
# Slavic
#
  sla:
    output: true
#
# Swedish_Sign_Language
#
  swl:
    output: true
#
# Serbian
#
  sr:
    output: true
#
# Somali
#
  so:
    output: true
#
# Kurmanji
#
  kmr:
    output: true
#
# Sorani
#
  ckb:
    output: true
#
# Cantonese
#
  yue:
    output: true
#
# Slovak
#
  sk:
    output: true
#
# Marathi
#
  mr:
    output: true
#
# Belarusian
#
  be:
    output: true
#
# Lithuanian
#
  lt:
    output: true
#
# Dargwa
#
  dar:
    output: true
#
# North_Sami
#
  sme:
    output: true
#
# Upper_Sorbian
#
  hsb:
    output: true
#
# Romansh
#
  rm:
    output: true
#
# Naija
#
  pcm:
    output: true
#
# Old_French
#
  fro:
    output: true
#
# Armenian
#
  hy:
    output: true
#
# Maltese
#
  mt:
    output: true
#
# Afrikaans
#
  af:
    output: true
#
# Bangla
#
  bn:
    output: true
#
# Telugu
#
  te:
    output: true
#
# Tagset conversion tables (even for languages that do not have their sections yet)
#
  tagset-conversion:
    output: true
    permalink: /tagset-conversion/:path.html
#
# Meeting materials
#
  2015-08-23-uppsala:
    output: true
    permalink: /2015-08-23-uppsala/:path.html
  v2_prelim:
    output: true
    permalink: /v2_prelim/:path.html
  v2:
    output: true
    permalink: /v2/:path.html
  misc:
    output: true
    permalink: /misc/:path.html


excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.org/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
