source:       .
destination:  ./_site
markdown:     kramdown
# kramdown:
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

# testing for redirect-from
baseurl: "/docs"

gems:
  - jekyll-redirect-from

collections:
#
# Universal
#
  u-pos:
    output: true
    permalink: /u/pos/:path.html
  u-feat:
    output: true
    permalink: /u/feat/:path.html
  u-dep:
    output: true
    permalink: /u/dep/:path.html
  u-overview:
    output: true
  ext-feat:
    output: true
    permalink: /u/ext-feat/:path.html
#
# English
#
  en-pos:
    output: true
    permalink: /en/pos/:path.html
  en-feat:
    output: true
    permalink: /en/feat/:path.html
  en-dep:
    output: true
    permalink: /en/dep/:path.html
  en-overview:
    output: true
#
# Finnish
#
  fi-pos:
    output: true
    permalink: /fi/pos/:path.html
  fi-feat:
    output: true
    permalink: /fi/feat/:path.html
  fi-dep:
    output: true
    permalink: /fi/dep/:path.html
  fi-overview:
    output: true
#
# Swedish
#
  sv-pos:
    output: true
    permalink: /sv/pos/:path.html
  sv-feat:
    output: true
    permalink: /sv/feat/:path.html
  sv-dep:
    output: true
    permalink: /sv/dep/:path.html
  sv-overview:
    output: true
#
# Hungarian
#
  hu-pos:
    output: true
    permalink: /hu/pos/:path.html
  hu-feat:
    output: true
    permalink: /hu/feat/:path.html
  hu-dep:
    output: true
    permalink: /hu/dep/:path.html
  hu-overview:
    output: true
#
# Irish
#
  ga-pos:
    output: true
    permalink: /ga/pos/:path.html
  ga-feat:
    output: true
    permalink: /ga/feat/:path.html
  ga-dep:
    output: true
    permalink: /ga/dep/:path.html
  ga-overview:
    output: true
#
# Bulgarian
#
  bg-pos:
    output: true
    permalink: /bg/pos/:path.html
  bg-feat:
    output: true
    permalink: /bg/feat/:path.html
  bg-dep:
    output: true
    permalink: /bg/dep/:path.html
  bg-overview:
    output: true
#
# Template
#
  template-pos:
    output: true
    permalink: /template/pos/:path.html
  template-feat:
    output: true
    permalink: /template/feat/:path.html
  template-dep:
    output: true
    permalink: /template/dep/:path.html
  template-overview:
    output: true

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
