source:       .
destination:  ./_site
markdown:     kramdown
# kramdown:
#   parse_block_html: true # allow markdown in <div> etc.
permalink:    date
# safe:         true
markdown_ext: md

gems:
  - jekyll-redirect-from

collections:
  ud-pos:
    output: true
  ud-feat:
    output: true
  en-dep:
    output: true
  fi-dep:
    output: true
  ud-dep:
    output: true

excerpt_separator: "\n\n"

# URL configuration

home: "http://universaldependencies.github.io/docs/"
tracker: "https://github.com/universaldependencies/docs/issues"
git_raw: "https://raw.githubusercontent.com/universaldependencies/docs/pages-source"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
